# Generated by Django 4.1.5 on 2023-03-21 08:22

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmodel",
            name="content",
            field=froala_editor.fields.FroalaField(),
        ),
    ]
